config/routes.rb
Rails.application.routes.draw do
  resources :rateable_attributes
  resources :reviews
  resources :locations do
    resources :visits
    collection do
      get :places_search
      get :place_details
    end
  end
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/rateable_attribute.rb
class RateableAttribute < ApplicationRecord
  has_many :location_rateable_attributes
  has_many :locations, through: :location_rateable_attributes

  has_many :reviews
end

app/controllers/rateable_attributes_controller.rb
class RateableAttributesController < ApplicationController
  before_action :set_rateable_attribute, only: [:show, :edit, :update, :destroy]

  # GET /rateable_attributes
  def index
    @rateable_attributes = RateableAttribute.order(:title).all
  end

  # GET /rateable_attributes/1
  def show
  end

  # GET /rateable_attributes/new
  def new
    @form = RateableAttributeForm.new(RateableAttribute.new)
  end

  # GET /rateable_attributes/1/edit
  def edit
    @form = RateableAttributeForm.new(@rateable_attribute)
    @form.prepopulate!
  end

  # POST /rateable_attributes
  def create
    @form = RateableAttributeForm.new(RateableAttribute.new)
    if @form.validate(rateable_attribute_params)
      @form.save
      redirect_to @form.model, notice: 'Attribute was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /rateable_attributes/1
  def update
    @form = RateableAttributeForm.new(@rateable_attribute)
    p rateable_attribute_params
    if @form.validate(rateable_attribute_params)
      @form.save
      redirect_to @form.model, notice: 'Attribute was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /rateable_attributes/1
  def destroy
    @rateable_attribute.destroy
    redirect_to rateable_attributes_url, notice: 'Attribute was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_rateable_attribute
    @rateable_attribute = RateableAttribute.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def rateable_attribute_params
    params.require(:rateable_attribute).permit(:title, location_ids: [])
  end
end

app/helpers/rateable_attributes_helper.rb
module RateableAttributesHelper
end

app/views/rateable_attributes/_form.html.haml
.form
  = form_for @form do |form|
    - if @form.errors.any?
      .notification.is-danger#error_explanation
        %button.delete
        .content
          %h4.subline
            = pluralize(@form.errors.count, "error")
            prohibited this attribute from being saved:
          %ul
            - @form.errors.full_messages.each do |message|
              %li= message
    .field
      = form.label :name
      .control= form.text_field :title, class: 'input'

    = form.collection_check_boxes :location_ids, Location.all, :id, :name do |m|
      .field
        = m.label do
          = m.check_box
          = m.object.name

    .actions.buttons
      = link_to back_target, class: 'button' do
        %span.icon
          %i.material-icons  chevron_left
        %span Back
      = button_tag class: 'button is-primary' do
        %span.icon
          %i.material-icons save
        %span= @form.model.new_record? ? 'Create Attribute' : 'Update Attribute'

app/views/rateable_attributes/edit.html.haml
.content
  %h1 Editing Attribute
  = render 'form', rateable_attribute: @rateable_attribute, back_target: @rateable_attribute

app/views/rateable_attributes/index.html.haml
%p#notice= notice
%h1.title Attributes
%table.table.is-striped.is-fullwidth
  %thead
    %tr
      %th Title
      %th Locations
      %th
  %tbody
    - @rateable_attributes.each do |rateable_attribute|
      %tr
        %td= rateable_attribute.title
        %td= rateable_attribute.locations.size
        %td
          .buttons.is-pulled-right
            = link_to rateable_attribute, class: 'button' do
              %span.icon
                %i.material-icons visibility
              %span Details
            = link_to edit_rateable_attribute_path(rateable_attribute), class: 'button' do
              %span.icon
                %i.material-icons edit
              %span Edit
            = link_to rateable_attribute, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button is-danger' do
              %span.icon
                %i.material-icons delete
              %span Delete
%br/
= link_to new_rateable_attribute_path, class: 'button is-success' do
  %span.icon
    %i.material-icons add
  %span New Attribute

app/views/rateable_attributes/new.html.haml
.content
  %h1.title New Attribute
  = render 'form', form: @form, back_target: rateable_attributes_path

app/views/rateable_attributes/show.html.haml
%h1.title= @rateable_attribute.title

.content
  %h4.title Locations
  - if @rateable_attribute.locations.any?
    %table.table.is-striped.is-fullwidth
      %thead
        %tr
          %th Name
          %th City
          %th Attributes
          %th
      %tbody
        - @rateable_attribute.locations.each do |location|
          = render 'locations/location', location: location
  - else
    %p No Locations with this Attribute found

.buttons
  = link_to rateable_attributes_path, class: 'button' do
    %span.icon
      %i.material-icons  chevron_left
    %span Back

  = link_to edit_rateable_attribute_path(@rateable_attribute), class: 'button is-info' do
    %span.icon
      %i.material-icons edit
    %span Edit